from pathlib import Path
from html import escape

ROOT = Path(__file__).parent / "dist"
MAIL = "eurlazurepharm@gmail.com"
PHONE = "0660 456 457"
FACEBOOK = "https://www.facebook.com/share/1R3SXmtx3s/"
INSTAGRAM = "https://www.instagram.com/azurepharm2021?utm_source=qr&stkn=MXd4ZWpmeDU4dXU1Yw=="

nav = [
    ("index.html", "Accueil"),
    ("produits.html", "Nos produits"),
    ("entreprise.html", "Qui sommes-nous"),
    ("recherche.html", "Recherche & développement"),
    ("contact.html", "Contact"),
]

def shell(title, description, current, body):
    links = "".join(f'<a href="{url}"{(" aria-current=\"page\"" if url == current else "")}>{label}</a>' for url, label in nav)
    mobile_links = "".join(f'<a href="{url}"{(" aria-current=\"page\"" if url == current else "")}>{label}</a>' for url, label in nav)
    return f'''<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#101b40">
  <meta name="description" content="{escape(description, quote=True)}">
  <title>{escape(title)} · Azuré Pharm</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23101b40'/%3E%3Cpath d='M12 49 30 13l7 15-7 9-3-7-10 19z' fill='%235d57a5'/%3E%3Cpath d='M31 43c10-15 21-22 27-17 5 5-3 17-17 23l-4-7c10-4 15-10 13-12-3-2-10 4-18 16z' fill='%232d9ddb'/%3E%3C/svg%3E">
  <link rel="stylesheet" href="assets/site.css?v=5">
  <script src="assets/site.js?v=2" defer></script>
</head>
<body>
  <a class="skip-link" href="#contenu">Aller au contenu</a>
  <div class="topline"><div class="container topline-inner"><a href="mailto:{MAIL}">✉ &nbsp; {MAIL}</a><a href="tel:+213660456457">☎ &nbsp; {PHONE}</a></div></div>
  <header class="site-header">
    <div class="container header-inner">
      <a class="brand" href="index.html" aria-label="Azuré Pharm, accueil"><span class="brand-mark"><img src="assets/azure-pharm-logo.png" alt=""></span><span class="brand-name">AZURÉ <strong>PHARM</strong><small>Votre partenaire de confiance</small></span></a>
      <nav class="desktop-nav" aria-label="Navigation principale">{links}</nav>
      <a class="header-contact button button-inset" href="contact.html">Nous contacter <span aria-hidden="true">↗</span></a>
      <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Ouvrir le menu"><span></span><span></span><span></span></button>
    </div>
    <nav class="mobile-nav" id="mobile-nav" aria-label="Navigation mobile" hidden>{mobile_links}</nav>
  </header>
  <main id="contenu">{body}</main>
  <footer class="site-footer">
    <div class="container footer-main">
      <div class="footer-brand"><div class="footer-brand-name">AZURÉ PHARM<span>.</span></div><p>Votre partenaire de confiance.</p><p>Détergents désinfectants conçus pour les exigences du secteur de la santé.</p></div>
      <div><h2>Explorer</h2><a href="index.html">Accueil</a><a href="produits.html">Nos produits</a><a href="entreprise.html">L’entreprise</a><a href="recherche.html">Recherche & développement</a></div>
      <div><h2>Nous contacter</h2><a href="tel:+213660456457">0660 456 457</a><a href="tel:+213553779211">0553 779 211</a><a href="mailto:{MAIL}">{MAIL}</a><span>Dely Brahim, Alger, Algérie</span></div>
      <div><h2>Suivez-nous</h2><a href="{FACEBOOK}" target="_blank" rel="noopener noreferrer">Facebook ↗</a><a href="{INSTAGRAM}" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div>
    </div>
    <div class="container footer-bottom"><span>© 2026 Azuré Pharm. Tous droits réservés.</span><span>Ouled Moussa · Dely Brahim · Algérie</span></div>
  </footer>
</body>
</html>'''

pages = {
"index.html": ("Accueil", "Azuré Pharm fabrique des détergents désinfectants pour les établissements de santé en Algérie.", '''
<section class="hero hero-slider" aria-label="Présentation Azuré Pharm"><div class="hero-slide is-active"><img src="assets/production-illustration.png" alt="Illustration d’une ligne de production de produits d’hygiène"><div class="hero-shade"></div><div class="container hero-copy"><h1>Une production pensée<br>pour les espaces de soins.</h1><p>Azuré Pharm fabrique des détergents désinfectants pour les professionnels de santé en Algérie.</p><a class="button button-inset button-hero" href="entreprise.html">Découvrir l’entreprise <span aria-hidden="true">↗</span></a></div></div><div class="hero-slide"><img src="assets/azure-products-scene.png" alt="Présentation illustrative de la gamme Azuré Pharm"><div class="hero-shade"></div><div class="container hero-copy"><h1>Des solutions d’hygiène<br>pour chaque usage.</h1><p>Sols, surfaces hautes et instruments : découvrez nos trois familles de produits.</p><a class="button button-inset button-hero" href="produits.html">Voir nos produits <span aria-hidden="true">↗</span></a></div></div><div class="hero-slide"><img src="assets/azure-laboratory.png" alt="Illustration des projets de recherche Azuré Pharm"><div class="hero-shade"></div><div class="container hero-copy"><h1>Votre partenaire<br>de confiance.</h1><p>Depuis 2021, Azuré Pharm accompagne les exigences d’hygiène du secteur de la santé.</p><a class="button button-inset button-hero" href="recherche.html">Notre démarche <span aria-hidden="true">↗</span></a></div></div><div class="hero-dots" aria-label="Choisir une diapositive"><button class="is-active" type="button" aria-label="Voir la diapositive 1" aria-current="true"></button><button type="button" aria-label="Voir la diapositive 2"></button><button type="button" aria-label="Voir la diapositive 3"></button></div></section>
<div class="ticker" aria-label="Les domaines d’activité Azuré Pharm"><div>HYGIÈNE DES SOLS & SURFACES <span>✦</span> SURFACES HAUTES <span>✦</span> INSTRUMENTS MÉDICAUX <span>✦</span> HÔPITAUX <span>✦</span> CLINIQUES <span>✦</span> COLLECTIVITÉS</div></div>
<section class="section intro-section"><div class="container"><div class="gallery-title"><span>NOTRE SAVOIR-FAIRE</span><h2>Au service de la<br><em>confiance.</em></h2><p>Des produits d’hygiène pensés pour les espaces de soins, fabriqués en Algérie depuis 2021.</p></div><div class="expertise-panel"><div class="expertise-lead"><span class="eyebrow">AZURÉ PHARM</span><h3>Une expertise centrée sur les usages de santé.</h3><p>Notre activité relie fabrication locale, exigences d’hygiène et dialogue avec les professionnels pour répondre aux besoins du quotidien.</p><a class="button button-inset" href="entreprise.html">Découvrir notre entreprise ↗</a></div><div class="expertise-list"><div><span>01</span><strong>Production locale</strong><p>Une unité de production située à Ouled Moussa, en Algérie.</p></div><div><span>02</span><strong>Trois familles de produits</strong><p>Des solutions pour sols et surfaces, surfaces hautes et instruments.</p></div><div><span>03</span><strong>Culture de l’hygiène</strong><p>Une activité dédiée aux espaces de soins et à leurs exigences.</p></div></div></div></div></section>
<section class="section roadmap-section"><div class="container"><div class="section-heading roadmap-heading"><span class="eyebrow">PROCESSUS</span><h2>La trajectoire Azuré</h2><p>Un parcours clair du besoin d’hygiène à la mise à disposition des produits, avec une attention portée à chaque étape.</p></div><div class="roadmap" id="roadmap"><div class="roadmap-track" aria-hidden="true"><div class="roadmap-ball"></div><svg viewBox="0 0 52 2047" preserveAspectRatio="none"><path class="roadmap-path-bg" d="M26 0V314C12 314 1 326 1 339C1 352 11 364 26 364C41 364 51 353 51 339C51 325 28 318 26 339V636V654.5C13.5 654.5 1 664 1 679C1 694 12 703 26 703C40 703 50.5 692.5 50.5 679C49.2307 664.367 26 660 26 679V979V994.5C13.5 994.5 1 1003.5 1 1019C1 1034.5 12 1044 26 1043.5C37 1043 50.5 1035 50.5 1019C50.5 1003 28.5 1001 26 1019V1327V1338C13 1338 1 1348.5 1 1363C1 1377.5 13.5 1388 26 1388C38.5 1388 51 1381 51 1363C51 1345 26 1346 26 1363V1678.5C12.5 1678.5 1 1687.5 1 1703C1 1718.5 14 1727.5 26 1727.5C38 1727.5 50.5 1719 50.5 1703C50.5 1687 26 1687 26 1703V2047"/><path class="roadmap-path-progress" d="M26 0V314C12 314 1 326 1 339C1 352 11 364 26 364C41 364 51 353 51 339C51 325 28 318 26 339V636V654.5C13.5 654.5 1 664 1 679C1 694 12 703 26 703C40 703 50.5 692.5 50.5 679C49.2307 664.367 26 660 26 679V979V994.5C13.5 994.5 1 1003.5 1 1019C1 1034.5 12 1044 26 1043.5C37 1043 50.5 1035 50.5 1019C50.5 1003 28.5 1001 26 1019V1327V1338C13 1338 1 1348.5 1 1363C1 1377.5 13.5 1388 26 1388C38.5 1388 51 1381 51 1363C51 1345 26 1346 26 1363V1678.5C12.5 1678.5 1 1687.5 1 1703C1 1718.5 14 1727.5 26 1727.5C38 1727.5 50.5 1719 50.5 1703C50.5 1687 26 1687 26 1703V2047"/></svg></div><div class="roadmap-steps"><article class="roadmap-step"><div class="roadmap-card"><span>01</span><h3>Comprendre le besoin</h3><p>Identifier l’environnement, les surfaces concernées et les attentes des équipes de soins.</p></div></article><article class="roadmap-step"><div class="roadmap-card"><span>02</span><h3>Orienter vers une gamme</h3><p>Choisir parmi les solutions pour sols et surfaces, surfaces hautes ou instruments.</p></div></article><article class="roadmap-step"><div class="roadmap-card"><span>03</span><h3>Préparer la production</h3><p>Organiser la fabrication à partir des besoins et des informations produits nécessaires.</p></div></article><article class="roadmap-step"><div class="roadmap-card"><span>04</span><h3>Fabriquer à Ouled Moussa</h3><p>Inscrire la production dans l’activité de notre unité implantée en Algérie.</p></div></article><article class="roadmap-step"><div class="roadmap-card"><span>05</span><h3>Veiller à la qualité</h3><p>Garder les exigences d’hygiène du secteur de la santé au cœur de notre démarche.</p></div></article><article class="roadmap-step"><div class="roadmap-card"><span>06</span><h3>Accompagner la demande</h3><p>Rester disponibles pour les informations produits et les échanges avec les professionnels.</p></div></article></div></div></div></section>
<section class="section pale-section"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">NOS PRODUITS</span><h2>Une réponse à chaque besoin d’hygiène.</h2></div><p>Trois familles de produits dédiées aux hôpitaux, cliniques et collectivités.</p></div><div class="product-grid"><a class="product-card" href="produits.html#sols-surfaces"><img src="assets/product-sols-surfaces.png" alt="Visuel illustratif du détergent désinfectant sols et surfaces"><span class="card-index">01 / SOLS & SURFACES</span><h3>Détergents désinfectants sols et surfaces</h3><span class="card-link">Découvrir ↗</span></a><a class="product-card" href="produits.html#surfaces-hautes"><img src="assets/product-surfaces-hautes.png" alt="Visuel illustratif du détergent désinfectant surfaces hautes"><span class="card-index">02 / SURFACES HAUTES</span><h3>Détergents désinfectants surfaces hautes</h3><span class="card-link">Découvrir ↗</span></a><a class="product-card" href="produits.html#instruments"><img src="assets/product-instruments.png" alt="Visuel illustratif du nettoyant pré-désinfectant pour instruments"><span class="card-index">03 / INSTRUMENTS</span><h3>Nettoyants pré-désinfectants des instruments</h3><span class="card-link">Découvrir ↗</span></a></div><p class="image-disclaimer">Images de produits à titre d’illustration.</p></div></section>
<section class="section mission-band"><div class="container mission-grid"><span class="eyebrow">NOTRE MISSION</span><h2>Contribuer à un environnement de soins plus sûr.</h2><p>Azuré Pharm s’engage à répondre aux besoins d’hygiène des patients et du personnel soignant avec une production locale et une attention constante à la qualité.</p><a class="button button-inset button-dark" href="entreprise.html">En savoir plus <span aria-hidden="true">↗</span></a></div></section>
<section class="section"><div class="container location-teaser"><div><span class="eyebrow">ANCRAGE LOCAL</span><h2>Produire en Algérie,<br>au plus près des besoins.</h2><p>Unité de production à Ouled Moussa. Siège social à Dely Brahim, Alger.</p><a class="button button-inset" href="entreprise.html#implantations">Notre entreprise <span aria-hidden="true">↗</span></a></div><div class="location-photo"><img src="assets/production-illustration.png" alt="Vue illustrative d’une ligne de production de produits d’hygiène"><span>Visuel d’illustration</span></div></div></section>
<section class="contact-strip"><div class="container contact-strip-inner"><div><span class="eyebrow">UN BESOIN, UNE QUESTION ?</span><h2>Échangeons sur vos besoins.</h2></div><a class="button button-inset button-strip" href="contact.html">Nous contacter <span aria-hidden="true">↗</span></a></div></section>
'''),
"produits.html": ("Nos produits", "Découvrez les trois familles de détergents désinfectants Azuré Pharm pour les espaces de soins et les instruments.", '''
<section class="page-hero"><div class="container"><span class="eyebrow">NOS PRODUITS</span><h1>Des solutions pour chaque geste d’hygiène.</h1><p>Trois familles de produits dédiées aux besoins des hôpitaux, cliniques et collectivités.</p></div></section>
<section class="section page-intro"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">DÉCOUVRIR LA GAMME</span><h2>Trois usages, une même exigence d’hygiène.</h2></div><p>Explorez la famille de produits qui correspond à votre besoin. Notre équipe peut vous renseigner sur les informations et documents disponibles pour chaque référence.</p></div><div class="jump-grid"><a href="#sols-surfaces"><span>01</span><strong>Sols & surfaces</strong><small>Entretien des espaces de soins ↗</small></a><a href="#surfaces-hautes"><span>02</span><strong>Surfaces hautes</strong><small>Zones de contact et mobilier ↗</small></a><a href="#instruments"><span>03</span><strong>Instruments</strong><small>Étape de pré-désinfection ↗</small></a></div></div></section>
<section class="section"><div class="container product-list">
<article class="product-row" id="sols-surfaces"><div class="product-row-number">01</div><div><span class="eyebrow">SOLS & SURFACES</span><h2>Détergents désinfectants sols et surfaces</h2><p>Une gamme destinée à l’entretien des sols et des surfaces dans les environnements de soins et les espaces collectifs.</p><a class="button button-inset" href="contact.html?produit=Sols%20et%20surfaces">Demander des informations ↗</a></div><figure class="product-row-art"><img src="assets/product-sols-surfaces.png" alt="Visuel illustratif du produit pour sols et surfaces"><figcaption>Visuel d’illustration</figcaption></figure></article>
<article class="product-row" id="surfaces-hautes"><div class="product-row-number">02</div><div><span class="eyebrow">SURFACES HAUTES</span><h2>Détergents désinfectants surfaces hautes</h2><p>Des solutions consacrées à l’entretien des surfaces hautes et des zones de contact dans les établissements de santé.</p><a class="button button-inset" href="contact.html?produit=Surfaces%20hautes">Demander des informations ↗</a></div><figure class="product-row-art"><img src="assets/product-surfaces-hautes.png" alt="Visuel illustratif du produit pour surfaces hautes"><figcaption>Visuel d’illustration</figcaption></figure></article>
<article class="product-row" id="instruments"><div class="product-row-number">03</div><div><span class="eyebrow">INSTRUMENTS</span><h2>Nettoyants pré-désinfectants des instruments</h2><p>Une famille de produits destinée à l’étape de pré-désinfection des instruments utilisés par les professionnels de santé.</p><a class="button button-inset" href="contact.html?produit=Instruments">Demander des informations ↗</a></div><figure class="product-row-art"><img src="assets/product-instruments.png" alt="Visuel illustratif du produit pour instruments"><figcaption>Visuel d’illustration</figcaption></figure></article>
</div></section><section class="section pale-section"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">POUR LES PROFESSIONNELS</span><h2>Choisir avec les bonnes informations.</h2></div><p>Les établissements de santé n’ont pas tous les mêmes usages. Précisez votre contexte pour obtenir une réponse adaptée.</p></div><div class="editorial-grid"><article><span>01 / USAGE</span><h3>Décrivez la zone concernée</h3><p>Sols, surfaces hautes ou instruments : ce premier repère permet d’orienter la discussion vers la bonne famille.</p></article><article><span>02 / INFORMATION</span><h3>Demandez la documentation</h3><p>Contactez-nous pour connaître les références, présentations et documents disponibles à jour.</p></article><article><span>03 / ÉCHANGE</span><h3>Parlez de vos besoins</h3><p>Notre équipe échange avec les hôpitaux, cliniques et collectivités sur leurs demandes.</p></article></div></div></section><section class="section faq-section"><div class="container faq-layout"><div><span class="eyebrow">QUESTIONS FRÉQUENTES</span><h2>Les premières réponses.</h2><p>Pour les indications détaillées d’un produit, demandez toujours sa documentation spécifique.</p></div><div class="faq-list"><details><summary>Quels types de produits propose Azuré Pharm ?</summary><p>Trois familles sont présentées ici : détergents désinfectants pour sols et surfaces, pour surfaces hautes, et nettoyants pré-désinfectants des instruments.</p></details><details><summary>À quels établissements s’adressent ces gammes ?</summary><p>Azuré Pharm s’adresse notamment aux hôpitaux, aux cliniques et aux collectivités.</p></details><details><summary>Comment obtenir des informations sur une référence ?</summary><p>Utilisez le formulaire de contact ou appelez le 0660 456 457. Précisez la famille qui vous intéresse.</p></details></div></div></section><section class="contact-strip"><div class="container contact-strip-inner"><div><span class="eyebrow">INFORMATIONS PRODUITS</span><h2>Vous cherchez une solution adaptée ?</h2></div><a class="button button-inset button-strip" href="contact.html">Contacter Azuré Pharm <span aria-hidden="true">↗</span></a></div></section>
'''),
"entreprise.html": ("Qui sommes-nous", "Azuré Pharm, entreprise algérienne spécialisée depuis 2021 dans la fabrication de produits d’hygiène pour le secteur de la santé.", '''
<section class="page-hero"><div class="container"><span class="eyebrow">QUI SOMMES-NOUS ?</span><h1>Une entreprise engagée pour l’hygiène des soins.</h1><p>Azuré Pharm accompagne les acteurs de santé avec des produits conçus pour les exigences de leurs environnements.</p></div></section>
<section class="milestone-band"><div class="container milestone-grid"><div><strong>2021</strong><span>Début de l’activité</span></div><div><strong>03</strong><span>Familles de produits</span></div><div><strong>02</strong><span>Implantations en Algérie</span></div></div></section>
<section class="section"><div class="container story-grid"><div><span class="eyebrow">DEPUIS 2021</span><h2>Votre partenaire de confiance.</h2></div><div><p>Azuré Pharm est une entreprise spécialisée dans la fabrication de détergents désinfectants et de dispositifs destinés au secteur de la santé. Sa mission est de contribuer à un milieu propre et sécuritaire pour les patients comme pour le personnel soignant.</p><p>Les produits destinés aux établissements de soins s’inscrivent dans un cadre d’exigences strictes en matière d’hygiène et de qualité. Cette attention guide notre activité au quotidien.</p></div></div></section>
<section class="section company-purpose"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">NOTRE RÔLE</span><h2>Une activité dédiée aux lieux de soins.</h2></div><p>Notre raison d’être est de proposer des solutions d’entretien et de pré-désinfection aux professionnels qui veillent chaque jour sur les patients.</p></div><div class="editorial-grid"><article><span>01 / MISSION</span><h3>Contribuer à l’hygiène</h3><p>Les produits Azuré Pharm sont destinés à accompagner les besoins d’entretien des établissements de santé.</p></article><article><span>02 / PROXIMITÉ</span><h3>Produire en Algérie</h3><p>La production est implantée à Ouled Moussa et le siège social à Dely Brahim, Alger.</p></article><article><span>03 / PERSPECTIVE</span><h3>Continuer à évoluer</h3><p>Des projets de recherche et développement accompagnent l’évolution des besoins du secteur.</p></article></div></div></section>
<section class="section pale-section" id="implantations"><div class="container"><div class="section-heading"><span class="eyebrow">NOS IMPLANTATIONS</span><h2>Une présence au cœur de l’Algérie.</h2></div><div class="implant-grid"><div class="implant-image"><img src="assets/production-illustration.png" alt="Maquette illustrative d’une unité de production de produits d’hygiène"><span>Maquette illustrative — unité de production</span></div><div class="implant-info"><div><span class="location-number">01</span><h3>Unité de production</h3><p>Ouled Moussa, Algérie</p></div><div><span class="location-number">02</span><h3>Siège social</h3><p>Dely Brahim, Alger, Algérie</p></div></div></div></div></section>
<section class="section"><div class="container"><div class="section-heading"><span class="eyebrow">DOMAINES D’ACTIVITÉ</span><h2>Au service des professionnels.</h2></div><div class="sector-grid"><div><span>01</span><h3>Hôpitaux</h3><p>Des espaces de soins où l’entretien des surfaces et des instruments fait partie des besoins quotidiens.</p></div><div><span>02</span><h3>Cliniques</h3><p>Des structures qui recherchent des familles de produits adaptées à leurs différents espaces.</p></div><div><span>03</span><h3>Collectivités</h3><p>Des lieux accueillant du public et des équipes, avec des besoins réguliers en hygiène.</p></div></div><div class="quality-note"><strong>Qualité & normes</strong><p>Les références exactes des certifications ISO n’ont pas été communiquées. Contactez notre équipe pour obtenir les informations et documents officiels à jour.</p></div></div></section><section class="contact-strip"><div class="container contact-strip-inner"><div><span class="eyebrow">ÉCHANGEONS</span><h2>Découvrir Azuré Pharm de plus près.</h2></div><a class="button button-inset button-strip" href="contact.html">Prendre contact ↗</a></div></section>
'''),
"recherche.html": ("Recherche & développement", "Les projets de recherche et développement d’Azuré Pharm accompagnent l’évolution des besoins en hygiène du secteur de la santé.", '''
<section class="page-hero"><div class="container"><span class="eyebrow">RECHERCHE & DÉVELOPPEMENT</span><h1>Faire évoluer les solutions d’hygiène.</h1><p>Azuré Pharm mène des projets de recherche continus pour accompagner les besoins du secteur de la santé.</p></div></section>
<section class="section"><div class="container rd-grid"><figure class="rd-photo"><img src="assets/azure-laboratory.png" alt="Illustration de la recherche et du développement Azuré Pharm"><figcaption>Visuel d’illustration</figcaption></figure><div><span class="eyebrow">NOTRE DÉMARCHE</span><h2>Observer, améliorer, avancer.</h2><p>La recherche et le développement occupent une place dans les projets d’Azuré Pharm. Notre ambition est de faire progresser nos solutions en restant attentifs aux usages et aux exigences des professionnels de santé.</p><p>Pour connaître nos produits et nos projets en cours, échangez directement avec notre équipe.</p><a class="button button-inset" href="contact.html">Prendre contact <span aria-hidden="true">↗</span></a></div></div></section>
<section class="section pale-section"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">NOS AXES DE RÉFLEXION</span><h2>Une recherche liée au terrain.</h2></div><p>Les projets de recherche continus d’Azuré Pharm s’inscrivent dans la réalité des établissements de santé et dans l’évolution de leurs attentes.</p></div><div class="editorial-grid"><article><span>01 / USAGES</span><h3>Écouter les besoins</h3><p>Comprendre les différentes situations d’entretien des sols, des surfaces hautes et des instruments.</p></article><article><span>02 / GAMMES</span><h3>Faire évoluer les solutions</h3><p>Étudier les pistes d’amélioration qui peuvent répondre aux exigences des professionnels.</p></article><article><span>03 / DIALOGUE</span><h3>Rester en contact</h3><p>Échanger avec les acteurs du secteur pour relier les projets aux besoins concrets.</p></article></div></div></section>
<section class="section rd-focus"><div class="container rd-focus-grid"><div><span class="eyebrow">UNE DÉMARCHE CONTINUE</span><h2>Des questions utiles guident nos projets.</h2></div><div class="focus-list"><div><span>01</span><p>Quels usages demandent une réponse d’hygiène plus adaptée ?</p></div><div><span>02</span><p>Comment présenter les informations produits de manière plus claire ?</p></div><div><span>03</span><p>Quels besoins émergent dans les hôpitaux, cliniques et collectivités ?</p></div></div></div></section>
<section class="contact-strip"><div class="container contact-strip-inner"><div><span class="eyebrow">UN PROJET, UNE QUESTION ?</span><h2>Parlons de vos besoins.</h2></div><a class="button button-inset button-strip" href="contact.html">Écrire à Azuré Pharm ↗</a></div></section>
'''),
"contact.html": ("Contact", "Contactez Azuré Pharm à Dely Brahim, Alger, pour toute question sur ses détergents désinfectants.", '''
<section class="page-hero"><div class="container"><span class="eyebrow">CONTACT</span><h1>Parlons de vos besoins.</h1><p>Une question sur nos produits ou notre activité ? Notre équipe est à votre écoute.</p></div></section>
<section class="section contact-section"><div class="container contact-grid"><div class="contact-details"><span class="eyebrow">NOS COORDONNÉES</span><h2>Restons en contact.</h2><div class="detail-item"><span>E-mail</span><a href="mailto:eurlazurepharm@gmail.com">eurlazurepharm@gmail.com</a></div><div class="detail-item"><span>Téléphone</span><a href="tel:+213660456457">0660 456 457</a><a href="tel:+213553779211">0553 779 211</a></div><div class="detail-item"><span>Siège social</span><strong>Dely Brahim, Alger, Algérie</strong></div><div class="social-row"><a href="https://www.facebook.com/share/1R3SXmtx3s/" target="_blank" rel="noopener noreferrer">Facebook ↗</a><a href="https://www.instagram.com/azurepharm2021?utm_source=qr&amp;stkn=MXd4ZWpmeDU4dXU1Yw==" target="_blank" rel="noopener noreferrer">Instagram ↗</a></div></div><div class="form-card"><h2>Écrivez-nous</h2><p>Complétez le formulaire pour préparer votre message dans votre messagerie.</p><form id="contact-form"><div class="form-two"><label>Nom et prénom <span>*</span><input name="nom" autocomplete="name" required></label><label>Adresse e-mail <span>*</span><input name="email" type="email" autocomplete="email" required></label></div><label>Téléphone<input name="telephone" type="tel" autocomplete="tel"></label><label>Sujet <span>*</span><input name="sujet" required></label><label>Votre message <span>*</span><textarea name="message" rows="6" required></textarea></label><button class="button button-inset" type="submit">Préparer l’e-mail <span aria-hidden="true">↗</span></button><p class="form-note" id="form-note" role="status">Votre application de messagerie s’ouvrira pour l’envoi.</p></form></div></div></section>
<section class="section pale-section"><div class="container"><div class="section-heading split-heading"><div><span class="eyebrow">POUR ALLER PLUS VITE</span><h2>Une demande claire, une réponse plus utile.</h2></div><p>Indiquez le type d’établissement, la famille de produits concernée et les informations recherchées. Nous pourrons ainsi mieux comprendre votre demande.</p></div><div class="editorial-grid"><article><span>01 / PRODUIT</span><h3>Précisez la gamme</h3><p>Sols et surfaces, surfaces hautes ou instruments : mentionnez l’usage qui vous intéresse.</p><a href="produits.html">Voir les produits ↗</a></article><article><span>02 / CONTEXTE</span><h3>Présentez votre structure</h3><p>Hôpital, clinique ou collectivité : quelques mots suffisent pour situer votre besoin.</p><a href="entreprise.html">Découvrir l’entreprise ↗</a></article><article><span>03 / DOCUMENTS</span><h3>Demandez les détails</h3><p>Pour une référence ou une certification, sollicitez les informations officielles disponibles à jour.</p><a href="mailto:eurlazurepharm@gmail.com">Écrire un e-mail ↗</a></article></div></div></section>
<section class="section contact-locations"><div class="container"><div class="section-heading"><span class="eyebrow">NOS ADRESSES</span><h2>Présents en Algérie.</h2></div><div class="address-grid"><div><span>01 / SIÈGE SOCIAL</span><h3>Dely Brahim</h3><p>Alger, Algérie</p><a href="mailto:eurlazurepharm@gmail.com">Contacter le siège ↗</a></div><div><span>02 / PRODUCTION</span><h3>Ouled Moussa</h3><p>Algérie</p><a href="entreprise.html#implantations">Découvrir notre implantation ↗</a></div></div></div></section>
'''),
}

for filename, (title, description, body) in pages.items():
    (ROOT / filename).write_text(shell(title, description, filename, body), encoding="utf-8")
